version: "3"

services:
  postgres_locksmith:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=banking
    volumes:
      - ./postgres/:/var/lib/postgresql/data

